# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: action-go-shim
report_sizes: true
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
builds:
  - main: ./cmd/shim
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      ## <<Stencil::Block(stencilLdflags)>>
      ## <</Stencil::Block>>
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
      ## <<Stencil::Block(stencilExtraArch)>>
      ## <</Stencil::Block>>
    goos:
      - linux
      - darwin
      - windows
      ## <<Stencil::Block(stencilExtraOS)>>

      ## <</Stencil::Block>>
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  use: git

## <<Stencil::Block(extraReleaseOpts)>>
upx:
  - enabled: true
    compress: "9"
    lzma: true

archives:
  - formats: binary
## <</Stencil::Block>>
